# Generated by Django 4.2.6 on 2023-10-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                (
                    'id',
                    models.BigIntegerField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    'username',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ('is_moder', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
