name: Deploy-TTS

on:
  push:
    branches:
      - main

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_ALLOWED_HOSTS: "*"
          envkey_POSTGRES_DB: postgres
          envkey_POSTGRES_HOST: db
          envkey_POSTGRES_NAME: postgres
          envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          envkey_POSTGRES_PORT: 5432
          envkey_POSTGRES_USER: postgres
          envkey_SECRET_KEY: "django-insecure-1anolspcrdcxu!vj8c5x01b62=c8#$i0+&l@mib^tt30i+^&5z"

          file_name: .env

      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint
        run: docker-compose --profile development run --rm web sh -c "make lint"

      - name: Test
        run: docker-compose --profile development run --rm -u root web sh -c "pytest"

  deploy:
    needs: test-lint # This line ensures deploy only runs after test-lint
    runs-on: ubuntu-22.04
    steps:
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: abulaysov
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build web
        id: docker_build_backend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: abulaysov/tts-backend-${{ github.sha }}
