name: Deploy-TTS

on:
  push:
    branches:
      - main

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint
        run: docker-compose -f docker-compose.local.yml run --rm web sh -c "make lint"

      - name: Test
        run: docker-compose -f docker-compose.local.yml run --rm -u root web sh -c "pytest"

  deploy:
    needs: test-lint # This line ensures deploy only runs after test-lint
    runs-on: ubuntu-22.04
    steps:
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: abulaysov
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build web
        id: docker_build_backend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: abulaysov/tts-backend-${{ github.sha }}
