name: Lint-test

on:
  pull_request:
    branches:
      - main

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint and Test
        run: |
          touch .env
          echo POSTGRES_USER="postgres" >> .env
          echo POSTGRES_PORT=5432 >> .env
          echo POSTGRES_PASSWORD="postgres" >> .env
          echo POSTGRES_NAME="postgres" >> .env
          echo POSTGRES_HOST="db" >> .env
          echo SECRET_KEY="django-insecure-1anolspcrdcxu\!vj8c5x01b62=c8#$i0+&l@mib^tt30i+^&5z" >> .env
          echo POSTGRES_DB="postgres" >> .env
          echo ALLOWED_HOSTS="*" >> .env
          cat .env
          docker-compose --profile development run --rm  --env-file .env tts-backend-dev sh -c "make lint"
          docker-compose --profile development run --rm -u root --env-file .env tts-backend-dev sh -c "pytest"
