name: Lint-test

on:
  pull_request:
    branches:
      - main

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint and Test
        run: |
          echo "
          ALLOWED_HOSTS='*'
          POSTGRES_DB=postgres
          POSTGRES_HOST=db
          POSTGRES_NAME=postgres
          POSTGRES_PASSWORD=postgres
          POSTGRES_PORT=5432
          POSTGRES_USER=postgres
          SECRET_KEY='django-insecure-1anolspcrdcxu\!vj8c5x01b62=c8#$i0+&l@mib^tt30i+^&5z'
          " > .env
          docker-compose --profile development run --rm web sh -c "make lint"
          docker-compose --profile development run --rm -u root web sh -c "pytest"
