name: Lint-test

on:
  pull_request:
    branches:
      - main

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint and Test
        run: |
          git config --system --add safe.directory '*'
          docker-compose -f docker-compose-test.yml run --rm tts-backend-dev sh -c "make lint"
          docker-compose -f docker-compose-test.yml run --rm tts-backend-dev sh -c "pytest"
